version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kofounda:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - app_data:/app/data

volumes:
  app_data: 